server:
  port: 8082

mybatis:
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    username: root
    password: 'q1909321004Q_'
    url: 'jdbc:mysql://localhost:3306/chinasafetydb?useUnicode=true&characterEncoding=gb2312&useSSL=true&serverTimezone=UTC'
    driver-class-name: com.mysql.cj.jdbc.Driver