server:
  port: 8081

mybatis:
  config-location: classpath:mybatis-config.xml

spring:
  datasource:
    username: root
    password: 'q1909321004Q_'
    url: 'jdbc:mysql://localhost:3306/train?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC'
    driver-class-name: com.mysql.cj.jdbc.Driver